# Generated by Django 4.2.7 on 2023-12-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
